import type { Metadata } from "next";

import { InventoryAdjustmentForm, InventoryItemForm } from "@/components/admin/InventoryForms";
import { getAdminInventory } from "@/server/admin-inventory";

export const metadata: Metadata = { title: "Inventory | Admin" };

const statusStyles = { HEALTHY: "bg-emerald-400/10 text-emerald-300", INACTIVE: "bg-white/7 text-muted", LOW: "bg-orange/12 text-orange", OUT: "bg-red-400/10 text-red-300" } as const;
const statusLabels = { HEALTHY: "In stock", INACTIVE: "Inactive", LOW: "Low stock", OUT: "Out of stock" } as const;
const adjustmentLabels = { CORRECTION: "Count corrected", ORDER_USAGE: "Used by order", RESTOCK: "Stock added", WASTE: "Waste recorded" } as const;

export default async function AdminInventoryPage() {
  const inventory = await getAdminInventory();
  const alerts = inventory.items.filter((item) => item.status === "OUT" || item.status === "LOW");
  return (
    <main className="px-4 pb-12 pt-6 sm:px-6 sm:pt-8 xl:px-9" id="main-content">
      <header className="hero-reveal"><p className="text-[0.65rem] font-bold uppercase tracking-[0.2em] text-gold">Kitchen operations</p><h1 className="mt-3 font-display text-[2rem] font-medium leading-none tracking-[-0.045em] sm:text-[2.55rem]">Inventory</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted">Track ingredients, record movement, and catch shortages before service is affected.</p></header>

      <section aria-label="Inventory totals" className="hero-reveal hero-reveal-1 mt-7 grid grid-cols-2 gap-2 sm:max-w-3xl sm:grid-cols-4 sm:gap-3"><Metric label="Tracked" value={inventory.total.toLocaleString("en-US")} /><Metric label="Low stock" value={inventory.lowStock.toLocaleString("en-US")} tone={inventory.lowStock ? "warning" : undefined} /><Metric label="Out of stock" value={inventory.outOfStock.toLocaleString("en-US")} tone={inventory.outOfStock ? "danger" : undefined} /><Metric label="Stock value" value={formatMoney(inventory.inventoryValueCents)} /></section>

      {alerts.length ? <section aria-labelledby="stock-alerts-heading" className="hero-reveal hero-reveal-2 mt-7 rounded-2xl bg-orange/[0.075] p-5 sm:p-6"><div className="flex items-center gap-3"><AlertIcon /><div><p className="text-[0.61rem] font-bold uppercase tracking-[0.17em] text-orange">Action needed</p><h2 className="mt-1 font-display text-xl font-medium" id="stock-alerts-heading">Stock alerts</h2></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{alerts.map((item) => <div className="flex items-center justify-between gap-4 rounded-xl bg-background/45 px-4 py-3" key={item.id}><div className="min-w-0"><p className="truncate text-sm font-semibold">{item.name}</p><p className="mt-1 text-xs text-muted">Alert at {formatQuantity(item.lowStockThreshold)} {item.unit}</p></div><p className={`shrink-0 text-sm font-semibold ${item.status === "OUT" ? "text-red-300" : "text-orange"}`}>{formatQuantity(item.quantity)} {item.unit}</p></div>)}</div></section> : null}

      <details className="group hero-reveal hero-reveal-2 mt-7 overflow-hidden rounded-2xl bg-white/[0.04] open:bg-white/[0.05]"><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-4 px-5 py-4 marker:hidden sm:px-6 [&::-webkit-details-marker]:hidden"><div><p className="text-[0.61rem] font-bold uppercase tracking-[0.17em] text-gold">Quick action</p><h2 className="mt-1 font-display text-xl font-medium">Track a new item</h2></div><span className="grid size-10 place-items-center rounded-full bg-gold text-xl text-background transition-transform duration-300 group-open:rotate-45 motion-reduce:transition-none">+</span></summary><div className="border-t border-white/8 p-5 sm:p-6"><InventoryItemForm /></div></details>

      <section aria-labelledby="inventory-list-heading" className="hero-reveal hero-reveal-3 mt-8"><div><p className="text-[0.61rem] font-bold uppercase tracking-[0.17em] text-gold">Stock room</p><h2 className="mt-2 font-display text-xl font-medium tracking-[-0.03em] sm:text-2xl" id="inventory-list-heading">All inventory</h2></div>
        {inventory.items.length ? <div className="mt-5 grid gap-3 2xl:grid-cols-2">{inventory.items.map((item) => <details className="group overflow-hidden rounded-2xl bg-white/[0.035] transition-colors duration-300 open:bg-white/[0.05] hover:bg-white/[0.05]" key={item.id}><summary className="flex min-h-24 cursor-pointer list-none items-center gap-4 p-4 marker:hidden sm:p-5 [&::-webkit-details-marker]:hidden"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-gold/10 text-gold"><BoxIcon /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-sm font-semibold sm:text-base">{item.name}</h3><span className={`rounded-full px-2 py-1 text-[0.55rem] font-bold uppercase tracking-[0.09em] ${statusStyles[item.status]}`}>{statusLabels[item.status]}</span></div><p className="mt-2 font-display text-xl font-medium tabular-nums">{formatQuantity(item.quantity)} <span className="font-sans text-xs font-normal text-muted">{item.unit}</span></p><p className="mt-1 text-xs text-muted">{formatMoney(item.unitCostCents)} per {item.unit} · alert at {formatQuantity(item.lowStockThreshold)}</p></div><svg aria-hidden="true" className="size-5 shrink-0 text-muted transition-transform duration-300 group-open:rotate-180 group-open:text-gold motion-reduce:transition-none" fill="none" viewBox="0 0 24 24"><path d="m7 10 5 5 5-5" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.7" /></svg></summary><div className="grid gap-6 border-t border-white/8 p-4 sm:p-5 lg:grid-cols-2"><div><p className="mb-4 text-[0.61rem] font-bold uppercase tracking-[0.16em] text-gold">Adjust stock</p><InventoryAdjustmentForm item={item} /></div><div className="border-t border-white/8 pt-6 lg:border-l lg:border-t-0 lg:pl-6 lg:pt-0"><p className="mb-4 text-[0.61rem] font-bold uppercase tracking-[0.16em] text-gold">Item settings</p><InventoryItemForm item={item} /></div></div></details>)}</div> : <EmptyState />}
      </section>

      <section aria-labelledby="inventory-activity-heading" className="hero-reveal hero-reveal-3 mt-8 rounded-2xl bg-white/[0.035] p-5 sm:p-6"><div><p className="text-[0.61rem] font-bold uppercase tracking-[0.17em] text-gold">Movement log</p><h2 className="mt-2 font-display text-xl font-medium tracking-[-0.03em] sm:text-2xl" id="inventory-activity-heading">Recent activity</h2></div>{inventory.adjustments.length ? <ol className="mt-5 divide-y divide-white/8">{inventory.adjustments.map((entry) => <li className="grid gap-2 py-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center sm:gap-5" key={entry.id}><div className="min-w-0"><p className="text-sm font-semibold">{entry.itemName} · {adjustmentLabels[entry.type]}</p><p className="mt-1 text-xs leading-5 text-muted">{entry.actorName} · {formatDate(entry.createdAt)}{entry.note ? ` · ${entry.note}` : ""}</p></div><div className="flex items-center gap-3 sm:text-right"><span className={`text-sm font-semibold tabular-nums ${entry.delta > 0 ? "text-emerald-300" : "text-orange"}`}>{entry.delta > 0 ? "+" : ""}{formatQuantity(entry.delta)} {entry.unit}</span><span className="text-xs text-muted">→ {formatQuantity(entry.balanceAfter)}</span></div></li>)}</ol> : <p className="mt-5 text-sm text-muted">Stock changes will appear here.</p>}</section>
    </main>
  );
}

function Metric({ label, tone, value }: { label: string; tone?: "danger" | "warning"; value: string }) { return <div className="rounded-2xl bg-white/[0.04] px-3 py-4 sm:px-4"><p className={`font-display text-xl font-medium sm:text-2xl ${tone === "danger" ? "text-red-300" : tone === "warning" ? "text-orange" : ""}`}>{value}</p><p className="mt-1 text-[0.56rem] font-bold uppercase tracking-[0.12em] text-muted sm:text-[0.6rem]">{label}</p></div>; }
function AlertIcon() { return <span className="grid size-10 shrink-0 place-items-center rounded-full bg-orange/12 text-orange"><svg aria-hidden="true" className="size-5" fill="none" viewBox="0 0 24 24"><path d="M12 8v5m0 3h.01M4.5 19h15L12 5 4.5 19Z" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.6" /></svg></span>; }
function BoxIcon() { return <svg aria-hidden="true" className="size-5" fill="none" viewBox="0 0 24 24"><path d="M4 7.5 12 3l8 4.5v9L12 21l-8-4.5v-9ZM4 7.5l8 4.5 8-4.5M12 12v9" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.6" /></svg>; }
function EmptyState() { return <div className="mt-5 rounded-2xl bg-white/[0.035] px-5 py-14 text-center"><p className="text-sm font-semibold">No inventory is being tracked</p><p className="mt-2 text-xs text-muted">Add the first ingredient or kitchen supply above.</p></div>; }
function formatMoney(cents: number) { return new Intl.NumberFormat("en-US", { currency: "USD", maximumFractionDigits: 2, style: "currency" }).format(cents / 100); }
function formatQuantity(value: number) { return new Intl.NumberFormat("en-US", { maximumFractionDigits: 3 }).format(value); }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-US", { day: "numeric", hour: "numeric", minute: "2-digit", month: "short" }).format(new Date(value)); }
