import type { Metadata } from "next";
import Link from "next/link";

import { searchAdminWorkspace } from "@/server/admin-workspace";

export const metadata: Metadata = { title: "Search | Admin" };

export default async function AdminSearchPage({ searchParams }: { searchParams: Promise<{ q?: string | string[] }> }) {
  const params = await searchParams;
  const rawQuery = Array.isArray(params.q) ? params.q[0] ?? "" : params.q ?? "";
  const data = await searchAdminWorkspace(rawQuery);
  const sections = [...new Set(data.results.map((result) => result.section))];
  return <main className="px-4 pb-12 pt-6 sm:px-6 sm:pt-8 xl:px-9" id="main-content"><header className="hero-reveal"><p className="text-[0.65rem] font-bold uppercase tracking-[0.2em] text-gold">Workspace</p><h1 className="mt-3 font-display text-[2rem] font-medium leading-none tracking-[-0.045em] sm:text-[2.55rem]">Global search</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted">Results only include areas your role is allowed to access.</p></header><form className="hero-reveal hero-reveal-1 mt-7 flex max-w-3xl items-end gap-3 rounded-2xl bg-white/[0.04] p-4 sm:p-5" method="get"><label className="min-w-0 flex-1"><span className="text-[0.61rem] font-bold uppercase tracking-[0.15em] text-muted">Search workspace</span><input autoFocus className="mt-2 h-11 w-full border-b border-white/15 bg-transparent text-base text-foreground outline-none transition-colors placeholder:text-muted/55 focus:border-gold" defaultValue={data.query} name="q" placeholder="Order, customer, dish, enquiry…" type="search" /></label><button className="inline-flex min-h-11 items-center justify-center whitespace-nowrap rounded-full bg-gold px-5 text-[0.64rem] font-bold uppercase tracking-[0.12em] text-background transition-colors hover:bg-gold-light" type="submit">Search</button></form>{data.query.length < 2 ? <Empty title="Enter at least two characters" detail="Search across the parts of ComEat you manage." /> : data.results.length ? <div className="hero-reveal hero-reveal-2 mt-8 space-y-7">{sections.map((section) => <section aria-labelledby={`search-${section}`} key={section}><div className="flex items-center justify-between gap-4"><h2 className="font-display text-xl font-medium" id={`search-${section}`}>{section}</h2><p className="text-xs text-muted">{data.results.filter((result) => result.section === section).length} found</p></div><div className="mt-3 divide-y divide-white/8 overflow-hidden rounded-2xl bg-white/[0.035]">{data.results.filter((result) => result.section === section).map((result) => <Link className="flex min-h-16 items-center justify-between gap-4 px-4 py-3 transition-colors hover:bg-white/[0.045] sm:px-5" href={result.href} key={result.id}><div className="min-w-0"><h3 className="truncate text-sm font-semibold">{result.title}</h3><p className="mt-1 truncate text-xs text-muted">{result.detail}</p></div><span aria-hidden="true" className="shrink-0 text-gold">→</span></Link>)}</div></section>)}</div> : <Empty title="No results found" detail={`Nothing matched “${data.query}”. Try a name, email, order reference, or dish.`} />}</main>;
}

function Empty({ detail, title }: { detail: string; title: string }) { return <div className="hero-reveal hero-reveal-2 mt-8 rounded-2xl bg-white/[0.035] px-5 py-14 text-center"><p className="text-sm font-semibold">{title}</p><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-muted">{detail}</p></div>; }
