import type { Metadata } from "next";
import Link from "next/link";

import { getAdminNotificationCenter } from "@/server/admin-workspace";

export const metadata: Metadata = { title: "Notifications | Admin" };

const kindLabels = { EMAIL: "Email delivery", INQUIRY: "New enquiry", ORDER: "Incoming order", STOCK: "Stock alert" } as const;
const kindStyles = { EMAIL: "bg-red-400/10 text-red-300", INQUIRY: "bg-sky-400/10 text-sky-300", ORDER: "bg-gold/12 text-gold", STOCK: "bg-orange/12 text-orange" } as const;

export default async function AdminNotificationsPage() {
  const data = await getAdminNotificationCenter();
  return <main className="px-4 pb-12 pt-6 sm:px-6 sm:pt-8 xl:px-9" id="main-content"><header className="hero-reveal"><p className="text-[0.65rem] font-bold uppercase tracking-[0.2em] text-gold">Operations</p><h1 className="mt-3 font-display text-[2rem] font-medium leading-none tracking-[-0.045em] sm:text-[2.55rem]">Notifications</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted">Live operational items requiring attention from your role.</p></header><section aria-label="Notification summary" className="hero-reveal hero-reveal-1 mt-7 grid grid-cols-2 gap-2 sm:max-w-md"><Metric label="Needs attention" value={data.count} /><Metric label="Status" value={data.count ? "Open" : "Clear"} /></section>{data.notifications.length ? <section aria-labelledby="notification-list-heading" className="hero-reveal hero-reveal-2 mt-8"><div className="flex items-end justify-between gap-4"><h2 className="font-display text-xl font-medium" id="notification-list-heading">Attention queue</h2><p className="text-xs text-muted">Updates automatically on refresh</p></div><div className="mt-4 divide-y divide-white/8 overflow-hidden rounded-2xl bg-white/[0.035]">{data.notifications.map((item) => <Link className="grid gap-3 px-4 py-4 transition-colors hover:bg-white/[0.045] sm:grid-cols-[auto_minmax(0,1fr)_auto] sm:items-center sm:px-5" href={item.href} key={item.id}><span className={`w-fit rounded-full px-2.5 py-1 text-[0.56rem] font-bold uppercase tracking-[0.09em] ${kindStyles[item.kind]}`}>{kindLabels[item.kind]}</span><div className="min-w-0"><h3 className="truncate text-sm font-semibold">{item.title}</h3><p className="mt-1 truncate text-xs text-muted">{item.detail}</p></div><div className="flex items-center gap-3"><time className="text-xs text-muted" dateTime={item.createdAt ?? undefined}>{item.createdAt ? formatRelativeTime(item.createdAt) : "Current"}</time><span aria-hidden="true" className="text-gold">→</span></div></Link>)}</div></section> : <div className="hero-reveal hero-reveal-2 mt-8 rounded-2xl bg-white/[0.035] px-5 py-14 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-emerald-400/10 text-emerald-300"><CheckIcon /></span><p className="mt-4 text-sm font-semibold">Everything is clear</p><p className="mt-2 text-xs text-muted">No operational alerts need your attention.</p></div>}</main>;
}

function Metric({ label, value }: { label: string; value: number | string }) { return <div className="rounded-2xl bg-white/[0.04] px-4 py-4"><p className="font-display text-xl font-medium sm:text-2xl">{value}</p><p className="mt-1 text-[0.56rem] font-bold uppercase tracking-[0.12em] text-muted">{label}</p></div>; }
function CheckIcon() { return <svg aria-hidden="true" className="size-5" fill="none" viewBox="0 0 24 24"><path d="m5 12 4 4L19 6" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.7" /></svg>; }
function formatRelativeTime(value: string) { const elapsed = Date.now() - new Date(value).getTime(); const minutes = Math.max(1, Math.floor(elapsed / 60_000)); if (minutes < 60) return `${minutes}m ago`; const hours = Math.floor(minutes / 60); if (hours < 24) return `${hours}h ago`; return `${Math.floor(hours / 24)}d ago`; }
